Add Makefile
kube-storage/spec pull request #5
Opened 2021-02-09 07:43 UTC by raghavendra-talur

There has been a change in the protoc binary from version v1.12. For
more information refer to:
https://github.com/golang/protobuf/issues/1070.

This Makefile has been kept minimal to achieve the following:

1. Changes should be made to the replication.proto file in the root of
   the repo.
2. The generated code is split into two files now,
   lib/go/replication.pb.go and lib/go/replication_grpc.pb.go

TODO: Add validation methods to ensure that the generated files match
with the commited files.

Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>

2021-02-09 07:49 UTC, Madhu-1 reviewed
what is the minimum version of protoc is required?

we also need to add validation for the required  version, if its 
not present we need to install the required packages

2021-02-09 07:54 UTC, iamniting requested changes

2021-02-09 07:54 UTC, iamniting commented on Makefile
> +all: build
I guess we should make sure that we have all dependencies as well if not download them.

2021-02-18 21:22 UTC, raghavendra-talur commented
Obsolete. Refer to #11

2021-02-18 21:22 UTC, closed without merging